sys:
  register-url: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
eureka:
  client:
    serviceUrl:
      defaultZone: ${sys.register-url}
    enabled: true
logging:
  file: e://log/saas-${spring.profiles.active}/${spring.application.name}.log
spring:
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: saas-config
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest